site_name: Programa Quimbamba

theme:
  name: "material"

nav:
  - Presentación: index.md
  - Definiciones y especificación de requerimientos.md
  - Procedimientos.md
  - Descripción jerárquica.md
  - Descripción individual de los módulos.md